// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injection

import (
	"github.com/jinzhu/gorm"
	"github.com/teten-nugraha/golang-twitter-clone-api/api"
	"github.com/teten-nugraha/golang-twitter-clone-api/repository"
	"github.com/teten-nugraha/golang-twitter-clone-api/service"
)

// Injectors from wire.go:

func InitUserApi(db *gorm.DB) api.UserApi {
	userRepository := repository.ProviderUserRepository(db)
	userService := service.ProviderUserService(userRepository)
	userApi := api.ProviderUserAPI(userService)
	return userApi
}

func InitAuthAPI(db *gorm.DB) api.AuthApi {
	userRepository := repository.ProviderUserRepository(db)
	userService := service.ProviderUserService(userRepository)
	authApi := api.ProviderAuthApi(userService)
	return authApi
}

func InitTweetAPI(db *gorm.DB) api.TweetApi {
	tweetRepository := repository.ProviderTweetRepository(db)
	tweetService := service.ProviderTweetService(tweetRepository)
	tweetApi := api.ProviderTweetApi(tweetService)
	return tweetApi
}

func InitCommentAPI(db *gorm.DB) api.CommentApi {
	commentRepository := repository.ProviderCommentRepository(db)
	commentService := service.ProviderCommentService(commentRepository)
	commentApi := api.ProviderCommentApi(commentService)
	return commentApi
}
